# Generated by Django 5.2.13 on 2026-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='image_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
