# Generated by Django 5.2.13 on 2026-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_mediaitem_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
