# Generated by Django 5.2.13 on 2026-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_description_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
